const stages=[
  {label:'Missed HVAC call',title:'A homeowner calls after hours.',text:'The customer reaches voicemail at 9:42 PM. Instead of sitting there until morning, the lead gets a short acknowledgement asking what the system is doing.',rows:[['Customer','Waiting for reply'],['Issue','Waiting for reply'],['Callback','Waiting for reply']]},
  {label:'Symptom check',title:'The intake gets the useful details first.',text:'The reply asks whether the system is completely off, blowing warm air, leaking, or making a noise. It collects facts for the technician without trying to diagnose the equipment by text.',rows:[['Issue','A/C blowing warm'],['Service type','Emergency repair'],['Diagnosis','Not provided']]},
  {label:'Safety + location',title:'The shop gets enough context to respond responsibly.',text:'The intake checks whether anyone is vulnerable to the heat or cold, then captures the service address and best callback number. It does not promise an arrival time.',rows:[['Vulnerable tonight','Yes'],['Service address','1482 Oak Ridge Dr.'],['Callback','(713) 555-0148']]},
  {label:'Human handoff',title:'A real person takes the next step.',text:'The lead is sent to the existing on-call route with the facts collected. The shop decides whether to call, schedule, or escalate—no pretend dispatch and no made-up outcome.',rows:[['Lead captured','9:42 PM'],['Handoff route','On-call booking'],['Status','Human follow-up needed']]}
];
let current=0;const buttons=[...document.querySelectorAll('.demo-steps button')],label=document.querySelector('#demoLabel'),title=document.querySelector('#demoTitle'),text=document.querySelector('#demoText'),report=document.querySelector('#report'),next=document.querySelector('#next');
function render(){const s=stages[current];label.textContent=s.label;title.textContent=s.title;text.textContent=s.text;report.innerHTML='<strong>Lead details</strong>'+s.rows.map(([a,b])=>`<p><span>${a}</span><b>${b}</b></p>`).join('');buttons.forEach((button,index)=>button.classList.toggle('active',index===current));next.textContent=current===stages.length-1?'Demo complete':'Show the next step →';next.disabled=current===stages.length-1}
buttons.forEach((button,index)=>button.addEventListener('click',()=>{current=index;render()}));next.addEventListener('click',()=>{current=Math.min(current+1,stages.length-1);render()});document.querySelector('#year').textContent=new Date().getFullYear();
