const stages=[
  {label:'Missed call',title:'A homeowner calls after hours.',text:'The customer reaches voicemail at 9:42 PM. Instead of sitting there until morning, the lead gets a short acknowledgement asking for the basics.',rows:[['Customer','Waiting for reply'],['Address','Waiting for reply'],['Problem','Waiting for reply']]},
  {label:'Quick reply',title:'The customer gets a useful answer.',text:'The reply is short and practical. It asks for the address and what is happening, then points a real emergency toward the right immediate step.',rows:[['Customer','Homeowner'],['Address','1482 Oak Ridge Dr.'],['Problem','Leaking water heater']]},
  {label:'Job details',title:'The right person sees what they need.',text:'The booking contact receives the basic details and can decide whether to call, schedule, or hand the job to the on-call technician.',rows:[['Priority','Urgent'],['Booking route','On-call dispatcher'],['Status','Needs follow-up']]},
  {label:'Morning handoff',title:'The owner sees what happened.',text:'A plain report shows the captured lead, when it arrived, where it went, and whether it still needs action. No pretend revenue numbers.',rows:[['Lead captured','9:42 PM'],['Routed','9:44 PM'],['Outcome','Needs follow-up']]}
];
let current=0;const buttons=[...document.querySelectorAll('.demo-steps button')],label=document.querySelector('#demoLabel'),title=document.querySelector('#demoTitle'),text=document.querySelector('#demoText'),report=document.querySelector('#report'),next=document.querySelector('#next');
function render(){const s=stages[current];label.textContent=s.label;title.textContent=s.title;text.textContent=s.text;report.innerHTML='<strong>Lead details</strong>'+s.rows.map(([a,b])=>`<p><span>${a}</span><b>${b}</b></p>`).join('');buttons.forEach((button,index)=>button.classList.toggle('active',index===current));next.textContent=current===stages.length-1?'Demo complete':'Show the next step →';next.disabled=current===stages.length-1}
buttons.forEach((button,index)=>button.addEventListener('click',()=>{current=index;render()}));next.addEventListener('click',()=>{current=Math.min(current+1,stages.length-1);render()});document.querySelector('#year').textContent=new Date().getFullYear();
